<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <RootNamespace>eTasks_server.Client</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '-'))</AssemblyName>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Services\NovaPasta\**" />
    <Content Remove="Services\NovaPasta\**" />
    <EmbeddedResource Remove="Services\NovaPasta\**" />
    <None Remove="Services\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\eTasks-server.Models\eTasks-server.Models.csproj" />
  </ItemGroup>

</Project>
